### ISSUE TITLE
Error in eval(predvars, data, env) :    invalid 'envir' argument of type 'character'

### ISSUE THREAD

**Issue by lizhaozhi** [cartof/digitalDLSorter#3]
Hi, 

After runing estimateZinbwaveParams.R, I got following error:

Create gene model matrix without Covariates
Error in eval(predvars, data, env) : 
  invalid 'envir' argument of type 'character'
Calls: model.matrix ... model.matrix.default -> model.frame -> model.frame.default -> eval
Execution halted

Thanks in advance for any suggestions!

**Comment by cartof** [comment]
Could you provide the arguments you set to run estimateZinbwaveParams.R and the head of the "genesAnnotFile" you provide to it?

**Comment by lizhaozhi** [comment]
I figured it out. 
In estimateZinbwaveParams.R, line 249:
gdm <- model.matrix(~1, data =  genesAnnot[match(rownames(counts),genesAnnot[,geneIDColumn]),])

my "genesAnnotFile" only has one column. so that according to line 249 my input for model.matrix is a vector. 

I change line 249 to:
 gdm <- model.matrix(~1, data =  genesAnnot[match(rownames(counts),genesAnnot[,geneIDColumn]),, drop = FALSE])
to keep it as a data frame / matrix

**Comment by cartof** [comment]
Great!

Thanks to spot that problem. I'll change it straight away.

I hope everything else goes better.
