### ISSUE TITLE
Is there any way to accelerate the program?

### ISSUE THREAD

**Issue by lizhaozhi** [cartof/digitalDLSorter#4]
Hi,

I have been running estimateZinbwaveParams.R for days but got no model. 
my snRNA-seq data 17926 genes & 35140 cells. 

our server information:
MiB Mem : 385601.0 total, 166133.0 free, 216696.9 used,   2771.1 buff/cache
MiB Swap:   8192.0 total,   7674.6 free,    517.4 used. 166535.5 avail Mem 

**I tried to use more than 1 core to run this script but failed.** I believe it was because of memory. 
Now, I am running estimateZinbwaveParams.R with 1 core via the "screen" command.

I would appreciate **if you could provide some expected output: for example, what should happen after it shows 
"Run estimation process
2020-11-19 10:52:04 "**

**Is there any way to accelerate the program? for example, use GPU?**

Thank you

**Comment by cartof** [comment]
The ZinbWave estimation is not very efficient computationally and with 35k cells may become useless. I would suggest to subsample your cells (10k for example) providing a minimum number of cells per cluster, to have all represented, and calculate de ZinbWave params from that subsample. Later you can combine the new simulated cells with the full set of 35k cells to build the pseudo-bulk samples.

Nevertheless, with 35k cells you may have enough cells to build the pseudo-bulk samples without the need to amplify the single cell profiles with simulation.

**Comment by lizhaozhi** [comment]
> The ZinbWave estimation is not very efficient computationally and with 35k cells may become useless. I would suggest to subsample your cells (10k for example) providing a minimum number of cells per cluster, to have all represented, and calculate de ZinbWave params from that subsample. Later you can combine the new simulated cells with the full set of 35k cells to build the pseudo-bulk samples.
> 
> Nevertheless, with 35k cells you may have enough cells to build the pseudo-bulk samples without the need to amplify the single cell profiles with simulation.

Thank you for your advice. after 4 days. it finally finished...
I also subsampled the cells as you suggested. I would like to make a comparison.
