### ISSUE TITLE
generateTrainAndTestBulkProbMatrix.R bugs

### ISSUE THREAD

**Issue by lizhaozhi** [cartof/digitalDLSorter#5]
Please correct me if I was wrong.
I got some errors when I run generateTrainAndTestBulkProbMatrix.R. I think it probably because when you test the code. your test data contains 10 cell types.
However, the number of cell types should depend on the number of cell types user inputed.
my suggestion is that setup a vector of imax = the number of cell types from probPriors.txt:

imax <- nrow(probsDesign) 
trainProbsMatrix <- matrix(rep(0,imax),nrow=1,byrow = T) 
if (i > imax) i <- 1 # replace all (i > 9)

Best

**Comment by lizhaozhi** [comment]
Wherever, it shows 10, replace it with imax. 
p <- rep(0,imax)
d <- rdirichlet(n,rep(1,imax))
.....

**Comment by cartof** [comment]
Thanks a lot for the suggestion. Nevertheless I'm preparing an R package with it easier to work with, and it will have that option.
