### ISSUE TITLE
How many genes are used as the input to the model

### ISSUE THREAD

**Issue by amjass12** [cartof/digitalDLSorter#6]
Hi! 

I was just wondering , as i cannot find this in the manuscript, how many genes are are used as the input to the neural network?

thank you

**Comment by cartof** [comment]
It is in the paper, altough a bit obscure (Supp. Figure 2). Sorry about it.

34145 genes for the Breast Cancer model and 23039 genes for the CRC model.

**Comment by amjass12** [comment]
Thanks for the clarification!
